import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const neganFont = localFont({
  src: "../../public/font/Negan.otf",
  variable: "--font-negan",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${neganFont.variable} font-sans h-full antialiased`}
    >
      <body className="min-h-full flex flex-col overflow-x-hidden">{children}</body>
    </html>
  );
}
